// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PopfileNet.FunctionalTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ManageFolder_To_BucketMappingsFeature : object, global::Xunit.IClassFixture<ManageFolder_To_BucketMappingsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "Manage Folder-to-Bucket Mappings", "  As a user\n  I want to create, edit, and delete folder-to-bucket mappings\n  So t" +
                "hat I can control how emails from different folders are classified", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ManageFolder_To_BucketMappings.feature"
#line hidden
        
        public ManageFolder_To_BucketMappingsFeature(ManageFolder_To_BucketMappingsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("ManageFolder_To_BucketMappings.feature.ndjson", 19);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="View all available IMAP folders")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "View all available IMAP folders")]
        [global::Xunit.TraitAttribute("Category", "mapping-view")]
        public async global::System.Threading.Tasks.Task ViewAllAvailableIMAPFolders()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-view"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View all available IMAP folders", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.WhenAsync("I view the Folder Mappings section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("I should see all available IMAP folders listed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("each folder should show its current bucket assignment (or \"Not assigned\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Assign a folder to a bucket")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Assign a folder to a bucket")]
        [global::Xunit.TraitAttribute("Category", "mapping-create-edit")]
        public async global::System.Threading.Tasks.Task AssignAFolderToABucket()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-create-edit"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Assign a folder to a bucket", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("there is at least one folder without a bucket assignment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync("there is at least one bucket configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.WhenAsync("I select an unassigned folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.AndAsync("I choose a bucket from the dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("I save the mapping", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.ThenAsync("the folder should be shown as assigned to the selected bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
    await testRunner.AndAsync("the mapping should persist in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change a folder\'s bucket assignment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Change a folder\'s bucket assignment")]
        [global::Xunit.TraitAttribute("Category", "mapping-create-edit")]
        public async global::System.Threading.Tasks.Task ChangeAFoldersBucketAssignment()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-create-edit"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change a folder\'s bucket assignment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("there is a folder assigned to Bucket 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("there is a different Bucket 2 configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.WhenAsync("I select the folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.AndAsync("I choose Bucket 2 from the dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.AndAsync("I save the mapping", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.ThenAsync("the folder should be shown as assigned to Bucket 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 37
    await testRunner.AndAsync("the mapping should be updated in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Unassign a folder from its bucket")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Unassign a folder from its bucket")]
        [global::Xunit.TraitAttribute("Category", "mapping-create-edit")]
        public async global::System.Threading.Tasks.Task UnassignAFolderFromItsBucket()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-create-edit"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unassign a folder from its bucket", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.AndAsync("there is a folder assigned to a bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.WhenAsync("I select the folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.AndAsync("I choose to remove the assignment (select \"None\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.AndAsync("I save the mapping", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
    await testRunner.ThenAsync("the folder should be shown as \"Not assigned\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
    await testRunner.AndAsync("the mapping should be removed from the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Edit an existing folder-to-bucket mapping")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Edit an existing folder-to-bucket mapping")]
        [global::Xunit.TraitAttribute("Category", "mapping-edit")]
        public async global::System.Threading.Tasks.Task EditAnExistingFolder_To_BucketMapping()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-edit"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit an existing folder-to-bucket mapping", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
    await testRunner.AndAsync("there is a folder assigned to a bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
    await testRunner.WhenAsync("I select the folder\'s current bucket assignment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
    await testRunner.AndAsync("I choose a different bucket from the dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("I save the mapping", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.ThenAsync("the folder should be shown as assigned to the new bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
    await testRunner.AndAsync("the mapping should be updated in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Delete a folder-to-bucket mapping")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Delete a folder-to-bucket mapping")]
        [global::Xunit.TraitAttribute("Category", "mapping-delete")]
        public async global::System.Threading.Tasks.Task DeleteAFolder_To_BucketMapping()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-delete"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete a folder-to-bucket mapping", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync("there is a folder assigned to a bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.WhenAsync("I select the folder\'s bucket assignment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
    await testRunner.AndAsync("I choose to remove the assignment (select \"None\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
    await testRunner.AndAsync("I save the mapping", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
    await testRunner.ThenAsync("the folder should be shown as \"Not assigned\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 70
    await testRunner.AndAsync("the mapping should be removed from the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Attempt to assign a folder to a non-existent bucket")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Attempt to assign a folder to a non-existent bucket")]
        [global::Xunit.TraitAttribute("Category", "mapping-validation")]
        public async global::System.Threading.Tasks.Task AttemptToAssignAFolderToANon_ExistentBucket()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Attempt to assign a folder to a non-existent bucket", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 74
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 75
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.AndAsync("there is a folder configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.WhenAsync("I select the folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
    await testRunner.AndAsync("I attempt to assign it to a non-existent bucket ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
    await testRunner.ThenAsync("I should see an error message indicating the bucket does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 80
    await testRunner.AndAsync("the folder\'s assignment should remain unchanged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Attempt to assign a non-existent folder to a bucket")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Attempt to assign a non-existent folder to a bucket")]
        [global::Xunit.TraitAttribute("Category", "mapping-validation")]
        public async global::System.Threading.Tasks.Task AttemptToAssignANon_ExistentFolderToABucket()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Attempt to assign a non-existent folder to a bucket", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 83
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 84
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 85
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
    await testRunner.AndAsync("there is a bucket configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
    await testRunner.WhenAsync("I attempt to assign a non-existent folder to a bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
    await testRunner.ThenAsync("I should see an error message indicating the folder does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 89
    await testRunner.AndAsync("no changes should be made to any folder mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Attempt to assign with empty folder name")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Attempt to assign with empty folder name")]
        [global::Xunit.TraitAttribute("Category", "mapping-validation")]
        public async global::System.Threading.Tasks.Task AttemptToAssignWithEmptyFolderName()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Attempt to assign with empty folder name", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 94
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
    await testRunner.WhenAsync("I attempt to assign an empty folder name to a bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
    await testRunner.ThenAsync("I should see an error message indicating the folder name is required", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
    await testRunner.AndAsync("no changes should be made to any folder mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Attempt to assign with whitespace-only folder name")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Attempt to assign with whitespace-only folder name")]
        [global::Xunit.TraitAttribute("Category", "mapping-validation")]
        public async global::System.Threading.Tasks.Task AttemptToAssignWithWhitespace_OnlyFolderName()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Attempt to assign with whitespace-only folder name", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 100
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 101
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 102
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
    await testRunner.WhenAsync("I attempt to assign a whitespace-only folder name to a bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
    await testRunner.ThenAsync("I should see an error message indicating the folder name is required", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 105
    await testRunner.AndAsync("no changes should be made to any folder mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Mappings persist across application restarts")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Mappings persist across application restarts")]
        [global::Xunit.TraitAttribute("Category", "mapping-persistence")]
        public async global::System.Threading.Tasks.Task MappingsPersistAcrossApplicationRestarts()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-persistence"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mappings persist across application restarts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 108
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 109
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 110
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
    await testRunner.AndAsync("there is a folder assigned to a bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
    await testRunner.WhenAsync("I save the mapping", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
    await testRunner.AndAsync("I restart the application", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
    await testRunner.AndAsync("I navigate back to the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
    await testRunner.ThenAsync("the folder should still be shown as assigned to the same bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Complete folder mapping workflow")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Complete folder mapping workflow")]
        [global::Xunit.TraitAttribute("Category", "mapping-workflow")]
        public async global::System.Threading.Tasks.Task CompleteFolderMappingWorkflow()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-workflow"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Complete folder mapping workflow", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 118
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 119
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 120
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
    await testRunner.AndAsync("there are no existing folder mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
    await testRunner.AndAsync("there are at least two buckets configured (Bucket 1 and Bucket 2)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
    await testRunner.WhenAsync("I assign Folder A to Bucket 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
    await testRunner.AndAsync("I assign Folder B to Bucket 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
    await testRunner.ThenAsync("Folder A should be shown as assigned to Bucket 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 126
    await testRunner.AndAsync("Folder B should be shown as assigned to Bucket 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
    await testRunner.WhenAsync("I change Folder A\'s assignment to Bucket 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
    await testRunner.ThenAsync("Folder A should be shown as assigned to Bucket 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 129
    await testRunner.AndAsync("Folder B should still be shown as assigned to Bucket 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
    await testRunner.WhenAsync("I remove Folder B\'s assignment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
    await testRunner.ThenAsync("Folder B should be shown as \"Not assigned\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
    await testRunner.AndAsync("Folder A should still be shown as assigned to Bucket 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="UI displays folder mappings in clear table format")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "UI displays folder mappings in clear table format")]
        [global::Xunit.TraitAttribute("Category", "mapping-ui")]
        public async global::System.Threading.Tasks.Task UIDisplaysFolderMappingsInClearTableFormat()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-ui"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UI displays folder mappings in clear table format", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 135
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 136
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 137
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
    await testRunner.WhenAsync("I view the Folder Mappings section", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 139
    await testRunner.ThenAsync("I should see a table with columns: Folder Name, Assigned Bucket, Actions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 140
    await testRunner.AndAsync("each row should display the folder name, bucket assignment (or \"(None)\"), and act" +
                        "ion buttons", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
    await testRunner.AndAsync("unassigned folders should show \"(None)\" in the Assigned Bucket column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="UI shows success feedback after saving mapping")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "UI shows success feedback after saving mapping")]
        [global::Xunit.TraitAttribute("Category", "mapping-ui-feedback")]
        public async global::System.Threading.Tasks.Task UIShowsSuccessFeedbackAfterSavingMapping()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-ui-feedback"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UI shows success feedback after saving mapping", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 144
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 145
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 146
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
    await testRunner.AndAsync("there is a folder without a bucket assignment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 148
    await testRunner.AndAsync("there is a bucket configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 149
    await testRunner.WhenAsync("I select the folder", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 150
    await testRunner.AndAsync("I choose a bucket from the dropdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
    await testRunner.AndAsync("I save the mapping", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 152
    await testRunner.ThenAsync("I should see a success message indicating the mapping was saved", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="UI shows error feedback for invalid input")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "UI shows error feedback for invalid input")]
        [global::Xunit.TraitAttribute("Category", "mapping-ui-feedback")]
        public async global::System.Threading.Tasks.Task UIShowsErrorFeedbackForInvalidInput()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-ui-feedback"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UI shows error feedback for invalid input", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 155
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 156
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 157
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
    await testRunner.WhenAsync("I attempt to assign a folder to a non-existent bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 159
    await testRunner.ThenAsync("I should see an error message indicating the bucket does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="UI shows loading state during API calls")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "UI shows loading state during API calls")]
        [global::Xunit.TraitAttribute("Category", "mapping-ui-loading")]
        public async global::System.Threading.Tasks.Task UIShowsLoadingStateDuringAPICalls()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-ui-loading"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UI shows loading state during API calls", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 162
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 163
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 164
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 165
    await testRunner.WhenAsync("I perform an API operation (get mappings, save mapping, etc.)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
    await testRunner.ThenAsync("I should see a loading indicator during the operation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Multiple folders can be assigned to the same bucket")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Manage Folder-to-Bucket Mappings")]
        [global::Xunit.TraitAttribute("Description", "Multiple folders can be assigned to the same bucket")]
        [global::Xunit.TraitAttribute("Category", "mapping-multi-bucket")]
        public async global::System.Threading.Tasks.Task MultipleFoldersCanBeAssignedToTheSameBucket()
        {
            string[] tagsOfScenario = new string[] {
                    "mapping-multi-bucket"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple folders can be assigned to the same bucket", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 169
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 170
    await testRunner.GivenAsync("the UI is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 171
    await testRunner.AndAsync("I am on the Settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
    await testRunner.AndAsync("there are at least two folders without bucket assignments", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 173
    await testRunner.AndAsync("there is at least one bucket configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 174
    await testRunner.WhenAsync("I assign Folder 1 to the bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 175
    await testRunner.AndAsync("I assign Folder 2 to the same bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
    await testRunner.ThenAsync("both folders should be shown as assigned to the same bucket", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ManageFolder_To_BucketMappingsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ManageFolder_To_BucketMappingsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
