FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY *.dll .
COPY *.json .
COPY *.pdb .
COPY *.xml .

RUN useradd --create-home appuser && chown -R appuser /app
USER appuser

EXPOSE 5001
ENTRYPOINT ["dotnet", "PopfileNet.Ui.dll"]