FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .

RUN useradd --uid 1000 --create-home appuser && chown -R appuser /app
USER appuser

EXPOSE 5000
ENTRYPOINT ["dotnet", "PopfileNet.Backend.dll"]