sonar.projectKey=blakharaz_PopfileNet

sonar.sources=.
sonar.exclusions=**/obj/**,**/bin/**,**/*.Tests/**,**/TestResults/**,.github/**,*.md

sonar.sourceEncoding=UTF-8
sonar.dotnet.version=10.0

sonar.coverage.exclusions=**/*.Tests/**,**/TestResults/**
