// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PopfileNet.Database;

#nullable disable

namespace PopfileNet.Database.Migrations
{
    [DbContext(typeof(PopfileNetDbContext))]
    [Migration("20260305073949_UpdateEmailAndFolderIds")]
    partial class UpdateEmailAndFolderIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PopfileNet.Common.Bucket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Buckets");
                });

            modelBuilder.Entity("PopfileNet.Common.Email", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Folder")
                        .HasColumnType("text");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ImapUid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Folder");

                    b.HasIndex("ImapUid", "Folder")
                        .IsUnique();

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("PopfileNet.Common.MailFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BucketId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BucketId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MailFolders");
                });

            modelBuilder.Entity("PopfileNet.Common.MailHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("MailHeader");
                });

            modelBuilder.Entity("PopfileNet.Database.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImapPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImapPort")
                        .HasColumnType("integer");

                    b.Property<string>("ImapServer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ImapUseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("ImapUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxParallelConnections")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PopfileNet.Common.Email", b =>
                {
                    b.HasOne("PopfileNet.Common.MailFolder", "FolderNavigation")
                        .WithMany()
                        .HasForeignKey("Folder")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("PopfileNet.Common.EmailId", "UniqueId", b1 =>
                        {
                            b1.Property<string>("EmailId")
                                .HasColumnType("text");

                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("UniqueId");

                            b1.Property<long>("Validity")
                                .HasColumnType("bigint")
                                .HasColumnName("Validity");

                            b1.HasKey("EmailId");

                            b1.ToTable("Emails");

                            b1.WithOwner()
                                .HasForeignKey("EmailId");
                        });

                    b.Navigation("FolderNavigation");

                    b.Navigation("UniqueId");
                });

             modelBuilder.Entity("PopfileNet.Common.MailFolder", b =>
                 {
                     b.HasOne("PopfileNet.Common.Bucket", "Bucket")
                         .WithMany("Folders")
                         .HasForeignKey("PopfileNet.Common.MailFolder", "BucketId");

                     b.Navigation("Bucket");
                 });

            modelBuilder.Entity("PopfileNet.Common.MailHeader", b =>
                {
                    b.HasOne("PopfileNet.Common.Email", "Email")
                        .WithMany("Headers")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Email");
                });

             modelBuilder.Entity("PopfileNet.Common.Bucket", b =>
                 {
                     // Navigation property for Folders collection is handled by the WithMany above
                 });

            modelBuilder.Entity("PopfileNet.Common.Email", b =>
                {
                    b.Navigation("Headers");
                });
#pragma warning restore 612, 618
        }
    }
}
